[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
#rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
rustflags = [
  "--cfg",  "espidf_time64",
  "-C", "overflow-checks=on",  # Enable overflow checks for integer operations
  "-C", "target-feature=-fp"
  ] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Note: these variables are not used when using pio builder (`cargo build --features pio`)
#ESP_IDF_VERSION = "release/v5.1"
#ESP_IDF_VERSION = "v5.0.1"
ESP_IDF_VERSION = "v5.0.2"


